expense_tracker/expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('', include('login_register.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expense_tracker/main/urls.py
from django.urls import path
from .views import (
    index, about, add_product, dashboard, 
    order_details, product_details, order_item_details,
    create_order_single_item, order_success,
    delete_order)

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('add-product', add_product, name='add_product'),
    path('dashboard/', dashboard, name='dashboard'),
    path('order/<int:pk>/', order_details, name='order_details'),
    path('product/<int:pk>/', product_details, name='product_details'),
    path('order-item/<int:pk>/', order_item_details, name='order_item_details'),
    path('create-order/single-item', create_order_single_item, name='create_order_single_item'),
    path('create-order/success/<int:pk>/', order_success, name='order_success'),
    path('order/<int:pk>/delete/', delete_order, name='delete_order'),
]

expense_tracker/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image_url = models.URLField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    url = models.URLField(max_length=2083)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    purchased_at = models.DateTimeField(blank=True)
    
    def __str__(self) -> str:
        return self.name
    

class Courier(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image_url = models.URLField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='couriers/', blank=True, null=True)
    url = models.URLField(max_length=2083)
    
    def __str__(self) -> str:
        return self.name
    

class OrderDelivery(models.Model):
    ORDER_STATUS_CHOICES = [
    ('Processing', 'Processing'),
    ('In-Transit', 'In-Transit'),
    ('Delivered', 'Delivered'),
    ('Cancelled', 'Cancelled'),
    ('Returned', 'Returned'),
    ('Refunded', 'Refunded'),
    ('Failed', 'Failed'),
    ('Delayed', 'Delayed'),
    ]
    
    order_status = models.CharField(
        max_length=10,
        choices=ORDER_STATUS_CHOICES,
        default='Processing',
    )
    courier = models.ForeignKey(Courier, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"Delivery #{self.pk} by {self.courier.name} - {self.order_status}"
    
class OrderItem(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.quantity}x '{self.product.name}' of Order #{self.order.pk} from {self.order.user.first_name} (#{self.order.user.pk})"

    def save(self, *args, **kwargs):
        self.subtotal = self.product.price * self.quantity
        super().save(*args, **kwargs)

class Order(models.Model):
    STATUS_CHOICES = [
        ('Processing', 'Processing'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_items = models.ManyToManyField(Product, through=OrderItem)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Processing')
    delivery = models.OneToOneField(OrderDelivery, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        first_name = self.user.first_name or "User"
        return "{}'s order - #{}".format(first_name, self.pk)
    

expense_tracker/main/forms.py
from django import forms
from main.models import Product, OrderItem
from PIL import Image, ImageOps
import requests
from io import BytesIO
from django.core.files.base import ContentFile


class OrderFormOneItem(forms.ModelForm):
    product_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    product_price = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    product_description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    product_image_url = forms.URLField(widget=forms.URLInput(attrs={'class': 'form-control'}))
    product_url = forms.URLField(widget=forms.URLInput(attrs={'class': 'form-control'}))
    product_purchased_at = forms.DateTimeField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'datepicker'}))
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = OrderItem
        fields = ['quantity']
        
    field_order = [
        'product_name',
        'product_price',
        'quantity'
        'product_description',
        'product_image_url',
        'product_url',
        'product_purchased_at',
    ]

    def save(self, order, commit=True):
        product = Product(
            name=self.cleaned_data['product_name'],
            price=self.cleaned_data['product_price'],
            description=self.cleaned_data['product_description'],
            image_url=self.cleaned_data['product_image_url'],
            url=self.cleaned_data['product_url'],
            purchased_at=self.cleaned_data['product_purchased_at']
        )

        # Handle the image
        if product.image_url:
            response = requests.get(product.image_url)
            img = Image.open(BytesIO(response.content))
            img = img.convert('RGB')  # Ensure image is in RGB mode

            # Calculate the new size preserving the aspect ratio
            img.thumbnail((300, 300), Image.LANCZOS)

            # Create a new image with a white background
            new_img = Image.new("RGB", (300, 300), (255, 255, 255))

            # Calculate the position to paste the resized image onto the white background
            paste_position = (
                (300 - img.size[0]) // 2,
                (300 - img.size[1]) // 2
            )

            # Paste the resized image onto the white background
            new_img.paste(img, paste_position)

            # Save the new image into a buffer
            buffer = BytesIO()
            new_img.save(fp=buffer, format='JPEG')
            file_name = f"{product.name}_compressed_gitignore.jpg"
            product.image.save(file_name, ContentFile(buffer.getvalue()), save=False)

        if commit:
            product.save()

        order_item = OrderItem(
            order=order,
            product=product,
            quantity=self.cleaned_data['quantity'],
            subtotal=product.price * self.cleaned_data['quantity']
        )

        if commit:
            order_item.save()

        return order_item


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'image_url', 'url','purchased_at']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image_url': forms.URLInput(attrs={'class': 'form-control'}),
            'url': forms.URLInput(attrs={'class': 'form-control'}),
            'purchased_at': forms.TextInput(attrs={'class': 'form-control', 'id': 'datepicker'})
        }
        
    def save(self, commit=True):
        instance = super(ProductForm, self).save(commit=False)

        if self.cleaned_data.get('image_url'):
            image_url = self.cleaned_data['image_url']
            response = requests.get(image_url)
            img = Image.open(BytesIO(response.content))
            img = img.convert('RGB')  # Ensure image is in RGB mode
            img = img.resize((300, 300))  # Resize image to desired dimensions

            buffer = BytesIO()
            img.save(fp=buffer, format='JPEG')
            file_name = f"{instance.name}_compressed_gitignore.jpg"
            instance.image.save(file_name, ContentFile(buffer.getvalue()), save=False)

        if commit:
            instance.save()
        return instance

expense_tracker/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm, OrderFormOneItem
from main.models import Order, OrderItem, Product
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect
from .forms import ProductForm

@login_required
def delete_order(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.delete()
    return redirect('dashboard')

@login_required
def order_success(request, pk):
    order = get_object_or_404(Order, pk=pk)
    return render(request, 'order_success.html', {'order': order})

@login_required
def order_item_details(request, pk):
    order_item = get_object_or_404(OrderItem, pk=pk)
    print(order_item)
    return render(request, 'order_item_details.html', {'order_item': order_item})

@login_required
def product_details(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'product_details.html', {'product': product})

@login_required
def order_details(request, pk):
    order = get_object_or_404(Order, pk=pk)
    return render(request, 'order_details.html', {'order': order})

@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('about')  # Replace 'product_list' with your desired redirect
        else:
            print(form.errors)  # Print form errors to console for debugging
    else:
        form = ProductForm()
    return render(request, 'add_product.html', {'form': form})

@login_required
def create_order_single_item(request):
    if request.method == 'POST':
        form = OrderFormOneItem(request.POST)
        if form.is_valid():
            order = Order.objects.create(user=request.user)  # Assuming the order is created here
            form.save(order=order)
            return redirect('order_success', pk=order.pk)  # Redirect to a success page or order details
    else:
        form = OrderFormOneItem()

    return render(request, 'create_order_single_item.html', {'form': form})

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

@login_required
def dashboard(request):
    orders = _get_user_orders(request)
    context = {"orders": orders, "user": request.user}
    print(context)
    return render(request, 'dashboard.html', context)

def _get_user_orders(request):
    user = request.user
    orders = Order.objects.filter(user=user)
    return orders

expense_tracker/main/templates/add_product.html
{% extends "base.html" %}

{% block title %}Add Product{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Add Product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Product</button>
    </form>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#datepicker').datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true,
                showMeridian: true
            });
        });
    </script>
</div>
{% endblock %}

expense_tracker/main/templates/create_order_single_item.html
{% extends "base.html" %}

{% block title %}Add Order as single Product{% endblock %}

{% block content %}
<h2>Order from single item</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save order</button>
</form>
<script type="text/javascript">
    $(document).ready(function(){
        $('#datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            todayHighlight: true,
            showMeridian: true
        });
    });
</script>
{% endblock %}

expense_tracker/main/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container mt-0">
    <h2>Hi {{ user.first_name }}! Welcome to your dashboard.</h2>
    {% include "order_list.html" %}
</div>

{% endblock %}

expense_tracker/main/templates/order_details.html
{% extends 'base.html' %}

{% block content %}
<div class="card mt-5">
    <div class="card-header">
        <h3>{{ order.user.first_name }}'s Order - #{{ order.id }}</h3>
    </div>
    <div class="card-body">
        <h5 class="card-title">Order Details</h5>
        <p><strong>Order ID:</strong> {{ order.id }}</p>
        <p><strong>Status:</strong> {{ order.get_status_display }}</p>
        <p><strong>Created At:</strong> {{ order.created_at }}</p>
        <p><strong>Updated At:</strong> {{ order.updated_at }}</p>
        <hr>
        <h5>Products</h5>
        {% include "order_items_list.html" %}
        <hr>
        <h5>Delivery Details</h5>
        {% if order.delivery %}
            <p><strong>Courier:</strong> {{ order.delivery.courier.name }}</p>
            <p><strong>Status:</strong> {{ order.delivery.order_status }}</p>
        {% else %}
            <p>Delivery details not available.</p>
        {% endif %}
    </div>
    <div class="card-footer text-end">
        <div class="d-flex justify-content-start">
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Back to Orders</a>
            <form method="POST" action="{% url 'delete_order' order.id %}" class="ms-2">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

expense_tracker/main/templates/order_item_details.html
{% extends 'base.html' %}

{% block content %}
<div class="card mt-5">
    <div class="card-header">
        <h3>{{ order_item.product.name }}</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4 d-flex justify-content-center">
                {% if order_item.product.image %}
                    <img src="{{ order_item.product.image.url }}" class="img-fluid" alt="{{ order_item.product.name }}">
                {% elif order_item.product.image_url %}
                    <img src="{{ order_item.product.image_url }}" class="img-fluid" alt="{{ order_item.product.name }}">
                {% else %}
                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="Placeholder Image">
                {% endif %}
            </div>
            <div class="col-md-8">
                <h5 class="card-title">Product Details</h5>
                <p><strong>Name:</strong> {{ order_item.product.name }}</p>
                <p><strong>Qnt:</strong> {{ order_item.quantity }}</p>
                <p><strong>Price:</strong> {{ order_item.product.price }} €</p>
                <p><strong>Subtotal:</strong> {{ order_item.subtotal }} €</p>
                <p><strong>Description:</strong> {{ order_item.product.description }}</p>
                <p><strong>Product URL:</strong> <a href="{{ order_item.product.url }}" target="_blank">{{ order_item.product.url }}</a></p>
                <p><strong>Created At:</strong> {{ order_item.product.created_at }}</p>
                <p><strong>Updated At:</strong> {{ order_item.product.updated_at }}</p>
                <p><strong>Purchased At:</strong> {{ order_item.product.purchased_at }}</p>
            </div>
        </div>
    </div>
    <div class="card-footer text-end">
        <a href="{% url 'dashboard' %}" class="btn btn-secondary">Back to Dashboard</a>
    </div>
</div>
{% endblock %}

expense_tracker/main/templates/order_items_list.html
{% for order_item in order.orderitem_set.all %}
    <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
                {% if order_item.product.image %}
                <img src="{{ order_item.product.image.url }}" alt="Product Icon" class="me-2" style="width: 24px; height: 24px;">
                {% endif %}
                <span class="badge bg-primary me-2">{{ order_item.quantity }}x</span>
                <a href="{% url 'order_item_details' order_item.pk %}" class="text-decoration-none" style="color: inherit;">{{ order_item.product.name }}</a>
            </div>
            <div class="d-flex align-items-center">
                <span class="me-2 text-muted">{{ order_item.product.price }}/Unt €</span>
                <span class="fw-bold">{{ order_item.subtotal }} €</span>
            </div>
        </div>
    </li>
{% endfor %}

expense_tracker/main/templates/order_list.html
<div class="mx-left" style="max-width: 60%;">
    <ul class="list-group mt-4">
        {% if orders %}
            {% for order in orders %}
                <li class="list-group-item">
                    <a href="{% url 'order_details' order.pk %}" class="text-primary text-decoration-none fw-bold">Order Number #{{ order.pk }}</a>
                    <ul class="list-group mt-2">
                        {% include "order_items_list.html" %}
                    </ul>
                </li>
            {% endfor %}
        {% else %}
            <li class="list-group-item">No orders found.</li>
        {% endif %}
    </ul>
</div>

expense_tracker/main/templates/order_success.html
{% extends "base.html" %}

{% block title %}Order Success!{% endblock %}

{% block content %}
<h1>Order Success! # <a href="{% url 'order_details' order.id %}">{{order.id}}</a></h1>
{% endblock %}

expense_tracker/main/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="card mt-5">
    <div class="card-header">
        <h3>{{ product.name }}</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
                {% elif product.image_url %}
                    <img src="{{ product.image_url }}" class="img-fluid" alt="{{ product.name }}">
                {% else %}
                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="Placeholder Image">
                {% endif %}
            </div>
            <div class="col-md-8">
                <h5 class="card-title">Product Details</h5>
                <p><strong>Name:</strong> {{ product.name }}</p>
                <p><strong>Price:</strong> {{ product.price }} €</p>
                <p><strong>Description:</strong> {{ product.description }}</p>
                <p><strong>Product URL:</strong> <a href="{{ product.url }}" target="_blank">{{ product.url }}</a></p>
                <p><strong>Created At:</strong> {{ product.created_at }}</p>
                <p><strong>Updated At:</strong> {{ product.updated_at }}</p>
                <p><strong>Purchased At:</strong> {{ product.purchased_at }}</p>
            </div>
        </div>
    </div>
    <div class="card-footer text-end">
        <a href="{% url 'dashboard' %}" class="btn btn-secondary">Back to Dashboard</a>
    </div>
</div>
{% endblock %}

expense_tracker/main/templates/product_details.html
{% extends 'base.html' %}

{% block content %}
<div class="card mt-5">
    <div class="card-header">
        <h3>{{ product.name }} #{{ product.id }}</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
                {% elif product.image_url %}
                    <img src="{{ product.image_url }}" class="img-fluid" alt="{{ product.name }}">
                {% else %}
                    <img src="https://via.placeholder.com/300" class="img-fluid" alt="Placeholder Image">
                {% endif %}
            </div>
            <div class="col-md-8">
                <h5 class="card-title">Product Details</h5>
                <p><strong>Name:</strong> {{ product.name }}</p>
                <p><strong>Price:</strong> {{ product.price }} €</p>
                <p><strong>Description:</strong> {{ product.description }}</p>
                <p><strong>Product URL:</strong> <a href="{{ product.url }}" target="_blank">{{ product.url }}</a></p>
                <p><strong>Created At:</strong> {{ product.created_at }}</p>
                <p><strong>Updated At:</strong> {{ product.updated_at }}</p>
                <p><strong>Purchased At:</strong> {{ product.purchased_at }}</p>
            </div>
        </div>
    </div>
    <div class="card-footer text-end">
        <a href="{% url 'dashboard' %}" class="btn btn-secondary">Back to Dashboard</a>
    </div>
</div>
{% endblock %}